.gitignore
ci/azure-pipelines.yml
tools/toolchain/fabric.js
tools/toolchain/network/docker-compose/docker-compose.yaml

Use logspout to capture the logs of all containers
and write to a file.
This can then be added to the Azure build report
Change-Id: I056755e975e6b391924330935488f7dd85934710

Add in capture of docker logs

---

ci/azure-pipelines.yml

As rush and pnpm are used, implement the npm audit
by instally the built artifacts to a fake directory with npm
and then running npm audit
Change-Id: I9a621b8653a4dbcdd41c056398f21db173447f9f

[FAB-13051] npm audit checks

---

ci/azure-pipelines.yml

Build failed with 401 error, "You must be logged in to publish packages."
Adding `npm config ls` to check the correct user config is being picked up and trying an `npm login` to see if that helps.

Add npm login to publish step

---

.gitattributes
rush.json

- Node.js less than 13
- add gitattributes so that the json file is highlighted correctly
in github
Change-Id: Iee0cc11a07a1013a730f03804bb310108260a348

[FABCN-365] Update rush node.js version

---

ci/azure-pipelines.yml
docs/404.md
docs/index.md

- fixed 404 page (should be JSDoc, not Javadoc)
- fixed Go SDK link

[FABCN-378] Update gh-pages

---

ci/azure-pipelines.yml

It looks like rushjs symlinking can cause issues with the CopyFiles task. Use a script instead as suggested in microsoft/azure-pipelines-tasks#9046

Improve build reliability

---

ci/azure-pipelines.yml

Temporarily raise audit level to moderate to work around current minimist audit failures
Can be reverted after grpc, rc, and tar dependecies have been updated to pull in updated versions of mkdirp and minimist

Update audit level

---

ci/azure-pipelines.yml
tools/getEdgeDocker.sh

Temporarily raise audit level to moderate to work around current minimist audit failures
Can be reverted after grpc, rc, and tar dependecies have been updated to pull in updated versions of mkdirp and minimist

Cherry pick to master: Update audit level & Update fabric docker image version number pull

---

COMPATIBILITY.md
docs/_jsdoc/tutorials/using-iterators.md

FABCN-391 Remove references to 2.0 and 2.0.0

---

COMPATIBILITY.md
CONTRIBUTING.md
TUTORIAL.md
apis/fabric-contract-api/README.md
apis/fabric-contract-api/package.json
apis/fabric-shim-api/package.json
ci/azure-pipelines.yml
libraries/fabric-shim-crypto/package.json
libraries/fabric-shim/package.json
rush.json
test/chaincodes/annotations/package.json
test/chaincodes/clientidentity/package.json
test/chaincodes/crosschaincode/package.json
test/chaincodes/crosschaincode2/package.json
test/chaincodes/crud/package.json
test/chaincodes/encryption/package.json
test/chaincodes/events/package.json
test/chaincodes/query/package.json
test/chaincodes/scenario/package.json
test/fv/package.json
test/fv/utils.js

Update to use Node 12.16.1

---

docs/_config.yml
docs/_includes/header.html

Replace branch links with single GitHub repo link
Also revert to release-2.0 jsdoc link since 2.1 has not been released yet

[FABCN-391] Update apidoc site header

---

apis/fabric-shim-api/types/index.d.ts
libraries/fabric-shim/types/index.d.ts

Updated both typescript definition files to match the case
and the existance of the implementation function.

[FABCN-394] Update typescript interface file

---

docs/_jsdoc/index.md
docs/index.md

Signed-off-by: NIKHIL E GUPTA <negupta@us.ibm.com>

Fix broken tutorials link

---

libraries/fabric-shim/lib/iterators.js
libraries/fabric-shim/test/unit/iterators.js
test/chaincodes/crud/chaincode.js
test/fv/crud.js

Errow was the new version of protobufjs used to create the bundle.js
gave a different property to the 'has more' field.  hasMore replaced
has_more
As this accessed as JS property it didn't fail, but meant only a limited
number could be accessed.
corrected, added test for 229 results.
bit of dead code pruning

[FABCN-397] State queries limited to 100 results

---

COMPATIBILITY.md

Stated that 1.4.5 and above are the versions that work with node 12
Added a better example for the use of the chaincode node runtime environment
variable

[FABCN-396] Add notes on minimum 1.4 module version for node 12

---

libraries/fabric-shim/lib/chaincode.js
libraries/fabric-shim/lib/handler.js
libraries/fabric-shim/test/unit/chaincode.js
libraries/fabric-shim/test/unit/handler.js
libraries/fabric-shim/test/unit/iterators.js

This patch divides the ChaincodeSupportClient class into two classes:
ChaincodeSupportClient, which represents a chaincode client that
connects to a peer, and ChaincodeMessageHandler, which handles messages
in communciation with the peer through a stream.
Because the latter part is common in both client and server model,
the ChaincodeMessageHandler class will be used in the future
implementation for a chaincode gRPC server.

[FABCN-408] Separate message handler from client

---

libraries/fabric-shim/protos/common/common.proto
libraries/fabric-shim/protos/common/configtx.proto
libraries/fabric-shim/protos/common/policies.proto
libraries/fabric-shim/protos/discovery/protocol.proto
libraries/fabric-shim/protos/gossip/message.proto
libraries/fabric-shim/protos/peer/chaincode_shim.proto
libraries/fabric-shim/protos/peer/collection.proto
libraries/fabric-shim/protos/peer/lifecycle/lifecycle.proto
libraries/fabric-shim/protos/peer/transaction.proto
libraries/fabric-shim/protos/transientstore/transientstore.proto

This is cherry-pick for release-2.x of #154
To prepare for the implementation of chaincode gRPC server, this patch
updates protobuf definitions to the latest ones.

[FABCN-407] Update protos (#154)

---

libraries/fabric-shim/lib/chaincode.js
libraries/fabric-shim/lib/server.js
libraries/fabric-shim/test/unit/chaincode.js
libraries/fabric-shim/test/unit/server.js

This patch adds the ChaincodeServer class to support the server mode of
chaincode.
It also adds the server() method, which creates a new instance of
the ChaincodeServer class, to the Shim class, the entrypoint of the
fabric-shim library.
Update for CLI and e2e tests will be posted in another JIRA issues and PRs.

[FABCN-409] Chaincode gRPC server w/o TLS

---

test/e2e/scenario.js
test/fv/utils.js
tools/toolchain/index.js
tools/toolchain/network/crypto-material/configtx.yaml
tools/toolchain/utils.js

This is cherry-picking of #158 to the release-2.x branch.
This patch enables v2.0 feature in the test Hyperledger Fabric network
and uses new lifecycle commands in the fv and e2e tests.

[FABCN-410] Use new lifecycle for fv/e2e tests

---

libraries/fabric-shim/lib/cmds/serverCommand.js
libraries/fabric-shim/lib/contract-spi/bootstrap.js
libraries/fabric-shim/test/unit/cmds/serverCommand.js
libraries/fabric-shim/test/unit/contract-spi/bootstrap.js

This patch adds a "server" command to the "fabric-chaincode-node" CLI.
The command starts the contracts as a chaincode server.
Example: fabric-chaincode-node server --chaincode-address 0.0.0.0:9999 \
--chaincode-id mycc_v0:a1233bb13227a05932

[FABCN-411] Add server command to CLI

---

rush.json

This patch upgrades pnpm to fix the "Could not find peer dependency
'google-auth-library'" error in CI.

Fix 'rush install' error in release-2.x

---

test/chaincodes/server/.dockerignore
test/chaincodes/server/Dockerfile
test/chaincodes/server/index.js
test/chaincodes/server/package.json
test/chaincodes/server/package/connection.json
test/chaincodes/server/package/metadata.json
test/e2e/scenario.js
test/e2e/server.js
tools/toolchain/fabric.js
tools/toolchain/network/docker-compose/docker-compose-base.yaml
tools/toolchain/network/external/build
tools/toolchain/network/external/detect
tools/toolchain/network/external/release

This patch adds new e2e test for the chaincode gRPC server feature.
The test performs as following:
- Create a package which contains server and cc information
- Build a container image of the chaincode
- Install the package into peers
- Obtain the installed package ID from the peers
- Start the chaincode container with the package ID
- Approve and commit the chaincode definition
- Invoke and query the chaincode
"rush test:e2e" will perform both tests for both server and client mode.
"start-fabric" is also modified to use external builder scripts.

[FABCN-413] Add e2e test for chaincode server

---

libraries/fabric-shim/types/index.d.ts

This patch updates the type defintion file for TypeScript to add classes
and interfaces related to the chaincode server feature.
Depends on #164

[FABCN-414] Update TypeScript definition

---

libraries/fabric-shim/package.json

@grpc/grpc-js@1.1.0 release seems to have caused the initial coms to the peer to fail. Dropping back to 1.0.3

[FABCN-415] Lock grpc-js to 1.0.3

---

ci/azure-pipelines.yml

 [FABCN-420]  Remove Azure pipeline warnings

---

ci/azure-pipelines.yml
tools/getEdgeDocker.sh
tools/toolchain/network/docker-compose/docker-compose-base.yaml

Fabric 2.2 removes official support for CouchDB 2.x.
The migration to 3.1 was to address fsync issues
in the underlying storage implementation in Couch.
This change moves to CouchDB 3.1 which requires the
user to now set an admin identity at startup.
Signed-off-by: Brett Logan <brett.t.logan@ibm.com>

Use Official CouchDB 3.1 Image

---

ci/azure-pipelines.yml
tools/getEdgeDocker.sh
tools/toolchain/network/docker-compose/docker-compose-base.yaml

Fabric 2.2 removes official support for CouchDB 2.x.
The migration to 3.1 was to address fsync issues
in the underlying storage implementation in Couch.
This change moves to CouchDB 3.1 which requires the
user to now set an admin identity at startup.
Signed-off-by: Brett Logan <brett.t.logan@ibm.com>

Use Official CouchDB 3.1 Image (#180)

---

README.md
RELEASING.md

[FABCN-422] Add release guide

---

libraries/fabric-shim-crypto/test/shim-crypto.js
libraries/fabric-shim/test/unit/handler.js
libraries/fabric-shim/test/unit/server.js

Signed-off-by: lesleyannj <lesleyannj@hotmail.com>

[FABCN-241] Remove to.be.ok

---

fabric-shim/lib/handler.js

Trace point incorrectly logging entire binary message payload
Causes OOM errors.

[FABCN-435] OOM on large arg size

---

apis/fabric-shim-api/package.json
apis/fabric-shim-api/types/index.d.ts
common/config/rush/pnpm-lock.yaml

JIRA: https://jira.hyperledger.org/browse/FABCN-430
This patch fixes the type definition for the second field in the
Timestamp, which is actually Long (int64).

[FABCN-430] Fix type for timestamp.second

---

apis/fabric-shim-api/package.json
apis/fabric-shim-api/types/index.d.ts
common/config/rush/pnpm-lock.yaml

This patch fixes the type definition for the second field in the
Timestamp, which is actually Long (int64).
Co-authored-by: Matthew B White <mbwhite@users.noreply.github.com>

[FABCN-430] Fix type for timestamp.second (#194)

---

docs/_config.yml

Hopefully just need to trigger a merge build to publish the 2.2 docs
Note: _config.yml is only used in the master branch build

Publish 2.2 api docs

---

ci/azure-pipelines.yml

Node versions did not match docker image. Also clarifies why unit tests cannot use
the correct version.

Update node versions

---

apis/fabric-contract-api/lib/contract.js

Fixes typo in `getName` function header

Fix typo on fabric-contract-api

---

ci/azure-pipelines.yml

Version and date variables couldn't be accessed.. looks like as the displayenv wasn't an explicit dependency it didn't work as you might expect

Need explicit dependency for variables

---

common/config/rush/pnpm-lock.yaml
libraries/fabric-shim-crypto/package.json
test/e2e/scenario.js

Don't like taking tests out, but the problem is something related to the pipeline and the peer reading an empty file.
This runs without issue locally, and in other circumstances.

Disable the chaincode-as-a-server  test

---

docs/_config.yml

A link is broken in the documentation page because
the name of the repository has been changed from master to main.
This PR fixes the dead link.
Signed-off-by: Nao Nishijima <nao.nishijima.xt@hitachi.com>

Fix a dead link in docs

---

apis/fabric-contract-api/types/index.d.ts

Logger in the Context type definition should be Logging

Correct Typescript export

---

libraries/fabric-shim/lib/contract-spi/chaincodefromcontract.js
libraries/fabric-shim/lib/handler.js
libraries/fabric-shim/test/unit/handler.js
test/chaincodes/crosschaincode/chaincode.js

The Node shim differs from the Go shim in that returns any chaincode generated errors as grpc errors.
In Go, it just returns the ProposalResponse message with a status 500 code and error message embedded in it.
This difference makes it hard to write consistent error handling code in Fabric (esp Gateway) and the SDKs.
This commit changes the Node shim error handler to behave the same as the Go shim.
Signed-off-by: andrew-coleman <andrew_coleman@uk.ibm.com>

Chaincode errors should be returned as COMPLETED

---

libraries/fabric-shim/lib/stub.js

stub.invokeChaincode() receives a parameter `args` which is
a string array having arguments to pass to the called chaicode.
However, the current document explains the `args` is byte[][].
This PR fixes the document issue above.
Signed-off-by: Yuki Kondo <yuki.kondo.ob@hitachi.com>

Fix Doc: Type of args in invokeChaincode() is string[]

---

ci/azure-pipelines.yml

Removed the cron for the nightly 1.4 builds; this isn't the LTS release now. We would only publish a 1.4 release in very special cases. 

Stop the nightly builds

---

apis/fabric-contract-api/package.json
libraries/fabric-shim-crypto/package.json

Recent builds have failed with the browserlist module reporting
(on stderr) that it was outdated. This is a dependency of nyc, code coverage.
nyc is 'resting' and not actively being maintained.
Rush version used here is not ignoring that warning, and build fails.
Can't alter the rush rebuild command to ignore warnings. It's really
just going on anything written to stderr.
So adding a redirect on the nyc command stderr-> stdout (2>&1)
Have checked that a drop in coverage does still cause a failure.

Build failure - ignorable warning not ignored

---

CHANGELOG.md
ci/azure-pipelines.yml

The jsdoc push to gh-pages is failing, possibly due to an expired GitHub PAT. Allow the step to fail for now in order to attempt another release.

Allow jsdoc push to fail

---

docker/fabric-nodeenv/docker.js

Ideally we could adjust the docker image in the core.yaml but that is buried deep in the fabric-samples network.
Adding a short docker tag in the locally built docker image is the current best approach and simplest.
Should help the interopts testing

Add in short version docker tag

---

common/config/rush/command-line.json

Fix test failure related to the use of 2.3.x peer binary. peer binary  2.3.x did not have calculatepackageid implemented, which fabric-samples now uses. Ideally tests should not depend on fabric-samples.
Signed-off-by: David Enyeart <enyeart@us.ibm.com>

Update release-2.2 to use Fabric v2.4.6

---

common/config/rush/command-line.json

Fix test failure related to the use of 2.4.0-beta. 2.4.0-beta did not have calculatepackageid implemented, which fabric-samples now uses. Ideally tests should not depend on fabric-samples.
Signed-off-by: David Enyeart <enyeart@us.ibm.com>

Update release-2.4 to use Fabric v2.4.6

---

test/fv/utils.js

Previously if chaincode deploy failed during fvt tests no message was logged making it impossible to troubleshoot. Now the chaincode deploy commands and results and logged.
Signed-off-by: David Enyeart <enyeart@us.ibm.com>

Add fv test chaincode deploy logging

---

libraries/fabric-shim/lib/contract-spi/bootstrap.js
libraries/fabric-shim/lib/handler.js
libraries/fabric-shim/lib/server.js
libraries/fabric-shim/test/unit/server.js
libraries/fabric-shim/test/unit/stub.js

- removed possible issue with stream referring to the correct value, due to difference in scoping between function() and ()=>{}
- ensured that in server mode, the promise was awaited for
- fixed the register message being sent as the wrong type
- note the addition of the delete call - for some reason this was picked up by the coverage tests which it never has been before...

Fix issues with server-mode

---

.github/workflows/build.yaml
common/config/rush/pnpm-lock.yaml
libraries/fabric-shim/lib/contract-spi/bootstrap.js
libraries/fabric-shim/lib/handler.js
libraries/fabric-shim/lib/server.js
libraries/fabric-shim/package.json
libraries/fabric-shim/test/unit/server.js
libraries/fabric-shim/test/unit/stub.js

This PR cherry-picks commits from release-2.5 to main: 
- 30125f689a872073a2c37d6c64cd683b04acd754 (Build multi-arch / arm64 hyperledger/fabric-nodeenv) 
- b35dee8d9eb574649889c02c96775c5781a7c1d2 (Pin grpc-js to 1.8.1) 
- 0bd21b79bab7b3e5b89f8f0c908b4e6f7aed72f4 (Update to use arrow functions)

Backport merge from release-2.5 to main

---

libraries/fabric-shim/lib/utils/statebased.js
libraries/fabric-shim/test/unit/utils/statebased.js

The nOutOf was missing.
'specifically' this line wasn't there before... 
```
policy.setNOutOf(nOutOf);
```

Fix the handling of the key endorsement policy

---

.github/workflows/pull_request.yaml
.github/workflows/push.yaml
.github/workflows/release.yaml
.github/workflows/schedule.yaml
.github/workflows/test.yaml

Refactor build workflows to allow reuse through workflow calls, and to make it easier to define different behaviour for different triggers.

Add scheduled builds

---

common/config/rush/pnpm-lock.yaml
libraries/fabric-shim/package.json

`fast-safe-stringify` is being used in `fabric-shim` (in `logger.js`), but is missing in the dependencies array of `package.json`.
Fixes #388 
Signed-off-by: Rinish Sam <36656347+CaptainIRS@users.noreply.github.com>

Add missing `fast-safe-stringify` dependency to `fabric-shim`

---

COMPATIBILITY.md

Update COMPATIBILITY.md to indicate v2.5 uses Node.js 18. Other cleanup is also included.

Update COMPATIBILITY.md for Node 18.

---

libraries/fabric-shim/lib/stub.js

Update SetEvent documentation to indicate that only a single chaincode event can be included in a transaction.

Update SetEvent documentation

---

common/config/rush/pnpm-lock.yaml
libraries/fabric-shim/lib/stub.js
libraries/fabric-shim/package.json
libraries/fabric-shim/test/unit/stub.js

These were not interpreted correctly from the protocol buffer transaction timestamp.
Closes #400

Fix Stub getTxTimestamp() and getDateTimestamp() functions

---

TUTORIAL.md

This very modest contribution corrects a small typo in the example file that is intended to be copied by the reader of the tutorial.

TUTORIAL.md: fix missing quote in package.json template

---

apis/fabric-shim-api/types/index.d.ts
libraries/fabric-shim/types/index.d.ts

Fix ChaincodeResponse definition and add new response types (#413)

---

docs/_jsdoc/index.md

Signed-off-by: Santosh Kumar <s7santosh@gmail.com>
https://github.com/hyperledger/fabric-chaincode-node/issues/419 Added doc update how to start chaincode as a service, and how to set grpc parameters in the startup

Added doc update how to start chaincode as a service, and how to set grpc parameters in the startup

---

.github/settings.yml
.github/workflows/pull_request.yaml
.github/workflows/release.yaml
.github/workflows/test.yaml
.gitignore
COMPATIBILITY.md
TUTORIAL.md
common/scripts/install-run-rush-pnpm.js
common/scripts/install-run-rush.js
common/scripts/install-run-rushx.js
common/scripts/install-run.js
docker/fabric-nodeenv/Dockerfile
docs/_jsdoc/tutorials/using-chaincodeinterface.md
docs/_jsdoc/tutorials/using-contractinterface.md
libraries/fabric-ledger/package.json
libraries/fabric-shim/cli.js
rush.json
test/chaincodes/clientidentity/package.json
test/chaincodes/crosschaincode/package.json
test/chaincodes/crosschaincode2/package.json
test/chaincodes/crud/package.json
test/chaincodes/events/package.json
test/chaincodes/ledger/package.json
test/chaincodes/privateData/package.json
test/chaincodes/query/package.json
test/chaincodes/scenario/package.json
test/fv/package.json
tools/scripts/updateversions.sh

- Code remains compatible with Node 18.
- Project continues to be built and tested with Node 18.
- Node 20 is used as the runtime for the nodeenv Docker image to allow chaincode access to latest Node features and security fixes.
Closes #409

Use Node 20

---

common/config/rush/pnpm-lock.yaml
libraries/fabric-shim/package.json

Bump grpc-js to 1.10.9.
Bump fabric-protos to 0.2.1.
Remove unused proto-loader.
Used `rush update` command.
Closes #427

Update gRPC dependency to address CVE-2024-37168

---

.github/workflows/pull_request.yaml
.github/workflows/scan.yaml
.github/workflows/vulnerability-scan.yaml

Previously the scan ran on the current state of the codebase. This fails to identify vulnerabilities in dependencies for the latest release version if those dependencies have already been updated in the development codebase. The gating factor for whether a new release is required should be whether the previous release contains vulnerabilities.
This change runs the scheduled vulnerability scan on the latest release tag. It also adds vulnerability scanning to pull request builds. This is purely informational. A scan failure does not fail the pull request build.

Run vulnerability scan on latest release version

---

tools/getEdgeDocker.sh
tools/toolchain/network/docker-compose/docker-compose-base.yaml
tools/toolchain/network/docker-compose/docker-compose-cli.yaml
tools/toolchain/network/docker-compose/docker-compose-tls.yaml
tools/toolchain/network/docker-compose/docker-compose.yaml

The images in Hyperledger Artifactory are no longer updated and are well over a year old. This change uses the public Docker images from Docker Hub.

Use public Fabric Docker images

---

COMPATIBILITY.md
docker/fabric-nodeenv/Dockerfile
docker/fabric-nodeenv/build.sh

Use Node 22 for chaincode Docker image

---

.github/workflows/release.yaml

The current GitHub Actions workflow builds and pushes separate Docker images for each registry. This results in the images published to each registry having a different hash, despite having the same version tag.
This change modifies the Docker publishing job in the release workflow so that a single step builds and publishes the same Docker image to all Docker registries. For reproducability, the timestamp of the image is also set to the last commit timestamp.

Push identical image to all Docker registries

---

.github/workflows/schedule.yaml

The rate of change in this repository is low. Reduce scheduled build frequency to weekly to save build resources.

Reduce scheduled build frequency

---

.github/workflows/release.yaml

Instead of relying on QEMU emulation to build multi-arch images, use native arm64 and amd64 build runners to build architecture-specific images, then publish multi-arch metadata with each of the image manifests.

Use native runners to build Docker images

---

.github/workflows/release.yaml

This is required to prevent parse errors if multiple image names are specified.

Quote Docker image name
