- ci/azure-pipelines.yml
Signed-off-by: Brett Logan <Brett.T.Logan@ibm.com>
> Fix Azure Pipelines

- .gitignore
- CONTRIBUTING.md
- ci/azure-pipelines.yml
- common/config/rush/command-line.json
- common/config/rush/npm-shrinkwrap.json
- docs/apidocs/docs.js
- libraries/fabric-shim-crypto/package.json
- libraries/fabric-shim/package.json
- rush.json
- test/e2e/package.json
- test/fv/crud.js
- test/fv/package.json
- test/fv/utils.js
- tools/azure-mocha-reporter/index.js
- tools/azure-mocha-reporter/package.json
- tools/getEdgeDocker.sh
- tools/logfiles.sh
- tools/toolchain/network/crypto-material/core.yaml
- tools/toolchain/network/docker-compose/docker-compose-base.yaml
- tools/toolchain/verdaccio/index.js
Changes in this PR
- update the pipeline file to include more comments, and the future cron script
- uploads log files, unit, fv and coverage outputs
- uploads the jsdoc API html
- uploads the tgz and docker image
- pulls the latest docker images for the master branch
-
> Rush log files

- build/test/network/docker-compose/docker-compose-base.yaml
- build/test/network/docker-compose/docker-compose.yaml
- build/test/setup.js
- ci/azure-pipelines.yml
> Allow the docker logs to be captured

- ci/azure-pipelines.yml
Same approach as the previous Jenkins scripts.
Change-Id: Ifcc770e84888718c7cd14ebb3ed52fcc96568795
> [FAB-16711] Push JSDoc to the ghpages repo

- .gitignore
- ci/azure-pipelines.yml
> Fix typos and whitespace

- ci/azure-pipelines.yml
> Fix publish command step

- common/config/rush/pnpm-lock.yaml
- libraries/fabric-shim/package.json
Updates dependencies to the latest compatible version and yargs
to version containing mem fix
> Fix npm audit warning

- fabric-contract-api/package-lock.json
- fabric-shim-crypto/package-lock.json
- fabric-shim/package-lock.json
- fabric-shim/package.json
> Fix handlebars & yargs vulnerabilities

- ci/azure-pipelines.yml
Authenticate using fabric-chainode-node-npm service connection which has been added to the azure project
Change-Id: I1991faa6eeaf639707cf624ca00abee66ecd31db
> Add npmAuthenticate to azure pipeline

- ci/scripts/publish_docker.sh
Signed-off-by: Matthew B. White <whitemat@uk.ibm.com>
> Fix typo in docker login cmd

- ci/azure-pipelines.yml
- ci/scripts/publish_docker.sh
Signed-off-by: Matthew B. White <whitemat@uk.ibm.com>
> correct docker img tag name

- apis/fabric-contract-api/package.json
- apis/fabric-shim-api/package.json
- common/config/rush/pnpm-lock.yaml
- libraries/fabric-shim-crypto/package.json
- libraries/fabric-shim/package.json
- test/fv/package.json
As this repo uses rush, the 'shrinkwrap' file needs to be updated as well.
Signed-off-by: Matthew B. White <whitemat@uk.ibm.com>
> [FAB-17090] Correctly update the dependabot changes.

- ci/azure-pipelines.yml
> Set npmjs registry

- ci/azure-pipelines.yml
> [FAB-16711] Prepare for 2.0 beta

- TUTORIAL.md
- docker/fabric-nodeenv/package.json
- docs/apidocs/package.json
- docs/apidocs/tutorials/using-contractinterface.md
- test/chaincodes/clientidentity/package.json
- test/chaincodes/crosschaincode/package.json
- test/chaincodes/crosschaincode2/package.json
- test/chaincodes/encryption/package.json
- test/e2e/package.json
- tools/azure-mocha-reporter/package.json
- tools/toolchain/package.json
Correct to Apache-2.0
Change-Id: I5fecf829a2530f4655a2dd84a275789ae5debd27
> [FABCN-353] License updates

- apis/fabric-contract-api/LICENSE
- apis/fabric-shim-api/LICENSE
- apis/fabric-shim-api/README.md
- libraries/fabric-shim-crypto/LICENSE
- libraries/fabric-shim-crypto/README.md
- libraries/fabric-shim/LICENSE
READMEs for shim-crypto and shim-api
Ensured the licenses are in the these as well.
Change-Id: I210aadc6be22005b425e130d1b6ce9dc12437543
> [FABCN-355] Added READMEs

- fabric-shim-crypto/README.md
> [FABCN-355] README.md for shim-crypto

- libraries/fabric-shim/test/unit/chaincode.js
Signed-off-by: lesleyannj <lesleyannj@hotmail.com>
> FABCN-241 - Remove to.be.ok

- ci/azure-pipelines.yml
Tag needs to include hyperledger to match the publish command
> Fix docker tag

- ci/azure-pipelines.yml
> [FABCN-378] Publish jsdoc to correct repo

- ci/azure-pipelines.yml
- docs/_includes/header.html
Fix paths/urls, and remove unnecessary files
> Fix gh-pages publish

- COMPATIBILITY.md
> [FABCN-382] fix compatibility.md title

- .gitignore
- apis/fabric-contract-api/package.json
- common/config/rush/pnpm-lock.yaml
- docs/_jsdoc.json
- libraries/fabric-ledger/.eslintignore
- libraries/fabric-ledger/.eslintrc.js
- libraries/fabric-ledger/.npmignore
- libraries/fabric-ledger/package.json
- libraries/fabric-ledger/src/Collection.ts
- libraries/fabric-ledger/src/Ledger.ts
- libraries/fabric-ledger/src/index.ts
- libraries/fabric-ledger/test/unit/Ledger.spec.ts
- libraries/fabric-ledger/tsconfig.json
- libraries/fabric-shim-crypto/package.json
- rush.json
- test/chaincodes/annotations/package.json
- test/chaincodes/ledger/chaincode.js
- test/chaincodes/ledger/index.js
- test/chaincodes/ledger/package.json
- test/fv/ledger.js
- tools/toolchain/verdaccio/index.js
> [FABCN-359] Add fabric-ledger project

- ci/azure-pipelines.yml
- docs/package.json
- libraries/fabric-shim/test/unit/cli.js
fabric-ledger is typescript however the jsdoc is currently generated from the built javascript so need to add a dependency to the docs package
> [FABCN-359] Add ledger dev dependency to docs

- docs/_jsdoc/tutorials/using-iterators.md
Signed-off-by: Dave K <d_kelsey@uk.ibm.com>
> FABCN-385 remove incorrect getHistoryForKey example

- docs/README.md
Signed-off-by: Ry Jones <ry@linux.com>
> Add readme to redirect to site

- CHANGELOG.md
- ci/azure-pipelines.yml
- ci/bumpVersion.sh
- ci/changelog.sh
- fabric-contract-api/package.json
- fabric-shim-crypto/package.json
- fabric-shim/package.json
- package.json
- release_notes/v1.4.5.txt
> Fabric Chaincode Node v1.4.5

- fabric-contract-api/package.json
- fabric-shim-crypto/package.json
- fabric-shim/package.json
- package.json
> [FABCN-386] Prepare next release 1.4.6

- ci/azure-pipelines.yml
- test/fv/crosschaincode.js
- test/fv/crud.js
> Re-enable tests

- apis/fabric-shim-api/types/index.d.ts
- libraries/fabric-shim/lib/stub.js
- libraries/fabric-shim/test/unit/stub.js
- test/chaincodes/clientidentity/chaincode.js
- test/fv/clientidentity.js
> [FABCN-381] Access localmspid

- docs/_jsdoc/tutorials/using-iterators.md
Signed-off-by: Johnny Da Costa <johnny.dacosta@he-arc.ch>
> fix: remove semicolon

- apis/fabric-contract-api/package.json
- ci/azure-pipelines.yml
- libraries/fabric-shim-crypto/package.json
- libraries/fabric-shim/package.json
- package.json
- test/fv/package.json
> Expand node engine version range

- tools/getEdgeDocker.sh
> FABCN-391 Use version 2.1 of fabric docker images

- apis/fabric-shim-api/package.json
- test/chaincodes/annotations/package.json
- test/chaincodes/clientidentity/package.json
- test/chaincodes/crosschaincode/package.json
- test/chaincodes/crosschaincode2/package.json
- test/chaincodes/crud/package.json
- test/chaincodes/encryption/package.json
- test/chaincodes/events/package.json
- test/chaincodes/query/package.json
- test/chaincodes/scenario/package.json
> FABCN-391 Update test/chaincodes to use node 10 and add a missing hat

- COMPATIBILITY.md
- TUTORIAL.md
- docker/fabric-nodeenv/Dockerfile
- docker/fabric-nodeenv/docker.js
- docs/_jsdoc/tutorials/using-chaincodeinterface.md
- docs/_jsdoc/tutorials/using-contractinterface.md
- reflect this in compatibility.md
- update some out of date tutorial lines
> FABCN-391 Set docker images to use node 10

- ci/azure-pipelines.yml
- docs/_config.yml
> FABCN-391 Build against release-2.x

- docs/_config.yml
> FABCN-391 Update master docs to reference release-2.x

- tools/toolchain/network/crypto-material/core.yaml
Signed-off-by: Brett Logan <brett.t.logan@ibm.com>
> Update install timeout

- ci/azure-pipelines.yml
- ci/templates/build-data.yaml
Publish to a minor version release directory except on the master branch
> [FABCN-391] Update publish JSDoc job

- ci/azure-pipelines.yml
- ci/templates/build-data.yaml
> [FABCN-391] Publish JSDoc to release-2.1

- ci/azure-pipelines.yml
> [FABCN-391] fix directory for api doc publish

- docs/_config.yml
Replace release-2.0 link with release-2.1
> [FABCN-391] Update jsdoc 2.x link

- ci/azure-pipelines.yml
- tools/getEdgeDocker.sh
- tools/toolchain/fabric.js
- tools/toolchain/network/docker-compose/docker-compose-base.yaml
- tools/toolchain/network/docker-compose/docker-compose-cli.yaml
Signed-off-by: Brett Logan <brett.t.logan@ibm.com>
> Cleanup Fabric Version Methodology

- apis/fabric-shim-api/types/index.d.ts
- libraries/fabric-shim/types/index.d.ts
Updated both typescript definition files to match the case
and the existance of the implementation function.
> [FABCN-394] Update typescript interface file (#128)

- libraries/fabric-shim/cli.js
- libraries/fabric-shim/package.json
- libraries/fabric-shim/test/unit/cli.js
Change from package.json to api parser configuration
> FABCN-401 Correct use of Yargs api

- docs/_jsdoc/index.md
- docs/index.md
Signed-off-by: NIKHIL E GUPTA <negupta@us.ibm.com>
cherry pick link fixes to 2.x release. Old links are fine in 1.4
Co-authored-by: NIKHIL E GUPTA <negupta@us.ibm.com>
> Fix broken tutorials link (#137)

- MAINTAINERS.md
Reformat file
Signed-off-by: Ry Jones <ry@linux.com>
> Nominate James Taylor for maintainership

- TUTORIAL.md
- docs/_jsdoc/tutorials/using-contractinterface.md
Updated to use 2.1 modules
Signed-off-by: Ry Jones <ry@linux.com>
Co-authored-by: Matthew B White <mbwhite@users.noreply.github.com>
> FABCN-405 Fix tutorial reference (#150)

- libraries/fabric-shim/protos/common/common.proto
- libraries/fabric-shim/protos/common/configtx.proto
- libraries/fabric-shim/protos/common/policies.proto
- libraries/fabric-shim/protos/discovery/protocol.proto
- libraries/fabric-shim/protos/gossip/message.proto
- libraries/fabric-shim/protos/peer/chaincode_shim.proto
- libraries/fabric-shim/protos/peer/collection.proto
- libraries/fabric-shim/protos/peer/lifecycle/lifecycle.proto
- libraries/fabric-shim/protos/peer/transaction.proto
- libraries/fabric-shim/protos/transientstore/transientstore.proto
To prepare for the implementation of chaincode gRPC server, this patch
updates protobuf definitions to the latest ones.
> [FABCN-407] Update protos

- fabric-shim/README.md
Signed-off-by: Ian Chen <iancodinghtml@gmail.com>
> fixed some url, was moved, in readme.md

- apis/fabric-contract-api/package.json
- libraries/fabric-shim/package.json
Work around for issue winstonjs/winston#1814
> Specify exact version of winston dependency

- docs/_config.yml
Replace 2.1 with latest 2.2 release
> Update doc releases

- apis/fabric-shim-api/types/index.d.ts
- libraries/fabric-shim/types/index.d.ts
Signed-off-by: winderica <winderica@gmail.com>
> Fix: ChaincodeStub.getMspID should be in lowerCamelCASE

- README.md
- RELEASING.md
> [FABCN-422] Add release guide

- README.md
- RELEASING.md
> [FABCN-422] Add release guide (#187)

- fabric-shim/package.json
> Update to grpc 12.24.3

- libraries/fabric-shim-crypto/test/shim-crypto.js
- libraries/fabric-shim/test/unit/handler.js
- libraries/fabric-shim/test/unit/server.js
Signed-off-by: lesleyannj <lesleyannj@hotmail.com>
> [FABCN-241] Remove to.be.ok

- test/chaincodes/annotations/package.json
Need current supported levels.
> [FABCN-433] Update typescript and @types/node

- package.json
- test/fv/annotations/package.json
> [FABCN-433] Updated typescrtip and @types/node

- ci/azure-pipelines.yml
> [FABCN-434] Add release-1.4 to nightly Azure pipelines

- CHANGELOG.md
- release_notes/v1.4.6.txt
> [FABCN-436] Release 1.4.6

- docs/_jsdoc/tutorials/annotated-contract-metadata.md
- docs/_jsdoc/tutorials/tutorials.json
- docs/_jsdoc/tutorials/using-iterators.md
> Tutorials updated

- docs/_jsdoc/tutorials/annotated-contract-metadata.md
- docs/_jsdoc/tutorials/tutorials.json
- docs/_jsdoc/tutorials/using-iterators.md
> v2.x tutorials updated

- docs/_jsdoc/tutorials/using-chaincodeinterface.md
- docs/_jsdoc/tutorials/using-contractinterface.md
> v1.4 tutorials updated

- fabric-contract-api/package.json
[FABCN-432]-Update class transformer dependency
Signed-off-by: lesleyannj <lesleyannj@hotmail.com>
> [FABCN-432]-Update class transporter dependency

- ci/azure-pipelines.yml
> Update builds for new release-2.2 branch

- ci/azure-pipelines.yml
> Set node version for jsdoc build

- TUTORIAL.md
- apis/fabric-contract-api/package.json
- apis/fabric-shim-api/package.json
- ci/azure-pipelines.yml
- docs/_jsdoc/tutorials/using-chaincodeinterface.md
- docs/_jsdoc/tutorials/using-contractinterface.md
- libraries/fabric-ledger/package.json
- libraries/fabric-shim-crypto/package.json
- libraries/fabric-shim/package.json
- test/chaincodes/annotations/package.json
- test/chaincodes/clientidentity/package.json
- test/chaincodes/crosschaincode/package.json
- test/chaincodes/crosschaincode2/package.json
- test/chaincodes/crud/package.json
- test/chaincodes/encryption/package.json
- test/chaincodes/events/package.json
- test/chaincodes/ledger/package.json
- test/chaincodes/query/package.json
- test/chaincodes/scenario/package.json
- test/chaincodes/server/package.json
- test/fv/package.json
> Update node/npm versions

- fabric-shim/lib/stub.js
- fabric-shim/test/unit/stub.js
> [FABCN-222] Iterator issue fixed

- apis/fabric-shim-api/types/index.d.ts
- libraries/fabric-shim/lib/stub.js
- libraries/fabric-shim/test/unit/stub.js
> [FABCN-425] getTxTimestamp fixed

- docs/_jsdoc/tutorials/annotated-contract-metadata.md
- docs/_jsdoc/tutorials/deep-dive-contract-interface.md
- libraries/fabric-shim/lib/contract-spi/bootstrap.js
- libraries/fabric-shim/test/unit/contract-spi/bootstrap.js
> [FABCN-439] Metadata issue solved

- docs/_jsdoc/tutorials/using-iterators.md
> [FABCN-429] Iterator tutorial updated

- docs/_jsdoc/tutorials/using-typescript-decorators.md
> [FABCN-388] Tutorial updated

- fabric-shim/package.json
> Update x509 library version

- libraries/fabric-shim/lib/cmds/startCommand.js
- libraries/fabric-shim/test/unit/cmds/chaincode.js
> [FABCN-351] CORE_PEER_ADDRESS issue fixed

- ci/templates/nightly-version-update.yaml
- docs/package.json
Added dependency to docs
Fixed find command
> Add in the missing dependency, adjust find command

- ci/templates/nightly-version-update.yaml
> Move azure variable to env variable

- ci/azure-pipelines.yml
- test/fv/utils.js
- tools/toolchain/network/docker-compose/docker-compose-tls.yaml
- tools/toolchain/utils.js
- set flag in CI
- add in paths to orgs's certs
- adding in missing logging container to docker-compose
> Enable TLS FV Tests

- tools/toolchain/verdaccio/index.js
> Pipeline publishing fixed

- libraries/fabric-shim/cli.js
- libraries/fabric-shim/test/unit/cli.js
- test/fv/annotations.js
> Shebang issue fixed [FABCN-438]

- apis/fabric-contract-api/lib/contract.js
- libraries/fabric-shim/cli.js
- libraries/fabric-shim/lib/cmds/metadata/lib/generate.js
- libraries/fabric-shim/lib/contract-spi/bootstrap.js
- libraries/fabric-shim/test/unit/cmds/metadata/lib/generate.js
- libraries/fabric-shim/test/unit/contract-spi/bootstrap.js
> Metadata generate updated [FABCN-447]

- common/config/rush/pnpm-lock.yaml
- libraries/fabric-shim-crypto/package.json
- test/e2e/scenario.js
Signed-off-by: Kestutis Gudynas <kestutis.gudynas@ibm.com>
> Disable server tests

- TUTORIAL.md
- ci/azure-pipelines.yml
- common/config/rush/command-line.json
- test/chaincodes/privateData/chaincode.js
- test/chaincodes/privateData/collection-config/collection.json
- test/chaincodes/privateData/index.js
- test/chaincodes/privateData/package.json
- test/e2e/scenario.js
- test/e2e/server.js
- test/fv/annotations.js
- test/fv/clientidentity.js
- test/fv/privateData.js
- test/fv/utils.js
- tools/toolchain/fabric.js
- tools/toolchain/network/docker-compose/docker-compose-cli.yaml
- tools/toolchain/utils.js
Signed-off-by: Kestutis Gudynas <kestutis.gudynas@ibm.com>
> Private data tests added

- common/config/rush/command-line.json
- test/fv/utils.js
Signed-off-by: Kestutis Gudynas <kestutis.gudynas@ibm.com>
Additionally, I deleted 2 functions that are no longer needed.
> Stop fabric command updated

- test/fv/utils.js
- tools/toolchain/utils.js
Signed-off-by: Kestutis Gudynas <kestutis.gudynas@ibm.com>
> Fix test network

- libraries/fabric-shim/types/index.d.ts
> Correct TS type definitions

- ci/templates/build-data.yaml
- Update build-data.yaml to fail if the subshell's fail
> CI Pipeline Fixes

- TUTORIAL.md
This simple PR adds a missing bracket to an example presented in the Tutorial
> add missing bracket

- docs/_jsdoc/tutorials/using-iterators.md
Signed-off-by: Rajat Sharma <connecttorajat@outlook.com>
> Fixing the "Working with iterators" documentation

- apis/fabric-shim-api/types/index.d.ts
- ci/azure-pipelines.yml
- common/config/rush/command-line.json
- libraries/fabric-shim/lib/handler.js
- libraries/fabric-shim/lib/stub.js
- libraries/fabric-shim/test/typescript/chaincode.ts
- libraries/fabric-shim/test/unit/handler.js
- libraries/fabric-shim/test/unit/stub.js
- libraries/fabric-shim/types/index.d.ts
- test/chaincodes/privateData/chaincode.js
- test/fv/privateData.js
- tools/getEdgeDocker.sh
Signed-off-by: fraVlaca <ocsenarf@outlook.com>
> added purgePrivateData function with tests

- ci/azure-pipelines.yml
Signed-off-by: fraVlaca <ocsenarf@outlook.com>
> fixed nodeenv image used in fvtest to be the one built locally

- .github/workflows/build.yaml
> Enabled GHA with template workflow

- TUTORIAL.md
code formatting
Signed-off-by: Matthias Sieber <manonthemat@users.noreply.github.com>
> updated tutorial

- .github/workflows/build.yaml
> Get builds on release-2.5 branch

- .github/workflows/build.yaml
- test/fv/ledger.js
> GHA Workflow

- .github/workflows/pull_request.yaml
- .github/workflows/push.yaml
- .github/workflows/release.yaml
- .github/workflows/schedule.yaml
- .github/workflows/test.yaml
Refactor build workflows to allow reuse through workflow calls, and to make it easier to define different behaviour for different triggers.
> Add scheduled builds

- .github/workflows/test.yaml
> Name the artefacts uploaded to ensure no collisions

- MAINTAINERS.md
> Nominate Mark Lewis as maintainer

- docs/_jsdoc.json
- docs/_jsdoc/index.md
Fix doc generation by removing broken link to fabric-ledger.
Update outdated links.
> Fix and update docs
